<?php
/**
 * Created by PhpStorm.
 * User: Linxb
 * Date: 2019-07-01
 * Time: 17:13
 */

namespace DesignPatterns\Observer\Tests;

use DesignPatterns\Observer\PHPer;
use DesignPatterns\Observer\PHPerObserver;
use PHPUnit\Framework\TestCase;

class ObserverTest extends TestCase
{
    protected $observer;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->observer = new PHPerObserver();
    }

    /**
     *  测试notify通知
     */
    public function testNotify()
    {
        $subject = new PHPer();
        $subject->attach( $this->observer );
        $subject->setVersion( '0.0.2' );
        $this->expectOutputString('version is updated' );
    }
}